### ISSUE TITLE
500 : Internal Server Error

### ISSUE THREAD

**Issue by arnoakavdb** [sabinus52/jeedom-smartlife#10]
Bonjour,
Lorsque j'introduis mes données de connections , que je sauvegarde et que je pousse le bouton de test je me retrouve toujours avec cette erreur alors que les données sont correctes. Peux tu m'aider a résoudre ce problème?
Merci

**Comment by sabinus52** [comment]
Bonjour,
Il indique quoi comme erreur ?
Pour plus d'info, mettre les logs en mode **debug**

**Comment by arnoakavdb** [comment]
il indique juste une erreur 500 et le log en debug donne ca : 

[2019-11-10 12:24:05][DEBUG] : SEARCH DEVICE : Start
[2019-11-10 12:24:05][DEBUG] : CONNECTION : arno******@gmail.com (32) smart_life
[2019-11-10 12:25:00][DEBUG] : CHECK CONNECTION : Start
[2019-11-10 12:25:00][DEBUG] : CONNECTION : arno*****@gmail.com (32) smart_life

rien de plus

**Comment by sabinus52** [comment]
Y a-t-il des erreurs aussi dans le log `http.error` à la même heure ?
Je te conseille de faire une mise à jour depuis le Market Jeedom pour voir si le problème persiste ou sinon essayer la commande indiquée sur le ticket https://github.com/sabinus52/jeedom-smartlife/issues/2#issuecomment-544270422

**Comment by arnoakavdb** [comment]
effectivement j'ai ceci comme erreur dans http.error au même moment:

[Sun Nov 10 12:24:02.706965 2019] [:error] [pid 24368] [client 192.168.1.13:52763] PHP Parse error:  syntax error, unexpected 'SWITCH' (T_SWITCH), expecting identifier (T_STRING) in /var/www/html/plugins/SmartLife/vendor/sabinus52/tuyacloudapi/src/Device/DeviceFactory.php on line 20, referer: https://arno********/index.php?v=d&m=SmartLife&p=SmartLife

**Comment by sabinus52** [comment]
Bizarre ce bogue !
C'est quoi la version de Jeedom ? et du système ?
Il faudrait réinstaller le plugin depuis le Market pour être sûr d'avoir la dernière version du plugin

**Comment by arnoakavdb** [comment]
Je suis sous la dernière version de jeedom 3 et sous un Synology en debian chroot version stretch.j'ai effacé la version github et repris sur le market mais toujours la même erreur

**Comment by sabinus52** [comment]
Ta version de PHP est apparemment insensible à la casse des constantes, ce qui n'est pas le fonctionnement normal de PHP (voir https://tutorialsclass.com/faq/is-php-a-case-sensitive-language)
Je peux contourner le problème en apportant des nouvelles modifications.

**Comment by arnoakavdb** [comment]
Ok aussinon quelle version de PHP me conseilles tu?
