### ISSUE TITLE
Problème d'installation

### ISSUE THREAD

**Issue by Ant1989** [sabinus52/jeedom-smartlife#12]
Bonsoir,

Je suis probablement une grosse quiche
Mais ça fait maintenant plusieurs heures que j'essaie en vain d'installer le plugin
Par github (les infos ne sont pas les bonnes) et par l'url le plugin "n'est pas installé"

Serait-il possible de faire un tuto pour le gros noob que je suis SVP

**Comment by scorpio686** [comment]
ID logique : SmartLife
Utilisateur : sabinus52
Dépôt : jeedom-smartlife
Branche : Master

Vous pourrez vous connecter via email ou votre numéro de téléphone utilisé lors de l'inscription à Tuya/SmartLife, personnellement je n'ai pas réussi via l'émail, aucun souci via le numéro de téléphone. Préfixe 33 pour la France, 32 pour la Belgique

**Comment by sabinus52** [comment]
Bonjour,

J'ai rajouté la commande pour pouvoir installer le plugin depuis Github https://github.com/sabinus52/jeedom-smartlife

**Comment by Ant1989** [comment]
Merci pour le coup de pouce ;-)
