### ISSUE TITLE
Un volet ne répond plus : [state] à 3 …

### ISSUE THREAD

**Issue by HerveKr** [sabinus52/jeedom-smartlife#13]
Salut !
Je viens de passer mon plugin de sa version Github à la version Jeedom : RAS
Ce soir descente des 4 volets (fonctionnait pleinement en version Github)
L’un d’eux ne repond pas ce soir mais il répond depuis l’appli smartlife.
J’ai donc passé mes logs Jeedom SmartLife en debug
et

[2019-11-12 18:17:34][DEBUG] : REFRESH 78034xxxxxxxxxxxxbf1 : Sabinus\TuyaCloudApi\Device\CoverDevice Object (     [id:protected] => 7803446xxxxxxxxxxxxbf1     [type:protected] => cover     [name:protected] => Volet Living Fenêtres     [icon:protected] => https://images.tuyaeu.com/smart/program_category_icon/clkg.png     [data:protected] => Array         (             [support_stop] => 1             [online] => 1             **[state] => 3**         )  )

pour tout ce qui concerne ce volet j’ai tjrs [state] à 3 … qq soit l'action.
Si je compare , c’est le seul qui a cette valeur .
(les autres volets c’est à 2)

Que comprendre ?
Que faire ?

Je précise également que aucun de mes volets n'apparait dans ifttt mais que tous fonctionnent depuis l'appli SmartLife.
Je précise également que suite à MaJ de l'appli Smart life je peux désactiver l'eclairage et le programmer (schedule, backlight et backlight schedule et un "triptime" qui est à 10s)
Autre précision: Comme sur l'appli je restais tjrs sur "opening ou closing" apres action, j'ai programmé un stop pour eviter cela (tjrs dans l'appli et en dehors des heures de fonctionnement depuis Jeedom)

Désolé de ttes ces précisions mais si cela peut etre utile.

**Comment by HerveKr** [comment]
Je pense avoir solutionné le pb plus haut : 
Depuis l'appli j'ai supprimé l'interrupteur,
Physiquement je l'ai réinitialisé
Puis je l'ai réintégré dans SmartLife
Ensuite dans Jeedom Plugin j'ai refait une découverte

Et ca semble fonctionner 
Je reviens vers toi si pb 

Merci !

**Comment by sabinus52** [comment]
Parfait !
J'ai fait pas mal de changement sur les volets roulants depuis le version 0.4 (bf88213).
Il était important dans certains cas de supprimer l'objet et de relancer une découverte.
