### ISSUE TITLE
Problème De Scènes

### ISSUE THREAD

**Issue by pierda40** [sabinus52/jeedom-smartlife#15]
Lorsque j'active une scène via jeedom (SI DETECTION PIR > ALLUMER LAMPE) la lampe s'allume directement sans detection. En espérant que vous arriverez à corriger ça. Au passage un grand merci pour votre travail

**Comment by sabinus52** [comment]
Le bouton "Activer" d'une scène permet de lancer une scène qui a été créé dans l'application SmartLife.
(SI DETECTION PIR > ALLUMER LAMPE) est ce un scénario Jeedom ou SmartLife ?

**Comment by pierda40** [comment]
Il s'agit du scénario créé dans l'application smartlife

**Comment by sabinus52** [comment]
C'est le fonctionnement normal de SmartLife.
Je pense que lorsqu'on exécute une scène SmartLife, çà exécute toutes les actions qui sont dans la scène.
Je ne suis pas convaincu par les scènes gérées dans SmartLife, qui sont trop simple en fonctionnalités. Il est plus judicieux de faire des scénarios dans Jeedom qui est bien plus puissant.

**Comment by pierda40** [comment]
Bonjour,
J'aimerai bien pouvoir faire un scénario dans Jeedom, mais il m'est
impossible d'utiliser mon detecteur PIR smartlife... c'est pour cela que ça
aurait pu fonctionner ainsi. Pensez-vous intégrer les détecteurs PIR
smartlife dans le plugin? Car ils sont à 7€ chez action, ce qui est plutôt
pas mal pour mon budget et il serait ainsi possible de profiter de la
puissance de jeedom pour les interactions.
Merci beaucoup pour vos réponses,

Pierre

**Comment by sabinus52** [comment]
Les détecteurs ne seront **jamais** pris en charge par ce plugin.
