### ISSUE TITLE
Aucun equipement decouvert

### ISSUE THREAD

**Issue by lynxium69** [sabinus52/jeedom-smartlife#17]
Bonjour Sabinus52,

Après avoir réussi a faire fonctionner le login mot de passe,  mon plugin ne détecte pas ma prise connectée.
Je n'ais plus aucunes erreur dans le plugin ni dans la détection, mais rien n'est détecté alors que je vois bien la prise connectée depuis mon iphone.

Merci de ton aide

**Comment by sabinus52** [comment]
Bonjour,
Il faudrait passer le plugin en mode debug et me communiquer les logs
