### ISSUE TITLE
Probleme a l'extinction d'un périphérique

### ISSUE THREAD

**Issue by rudak** [sabinus52/jeedom-smartlife#18]
Dans un scénario , je lance une commande simple qui se passe d'explications `#[bureau][ruban led ][Eteindre]#` et j'obtiens cette erreur...

`[2019-11-18 23:51:05][SCENARIO] Argument 1 passed to SmartLifeDevice::__construct() must be an instance of Sabinus\TuyaCloudApi\Device\Device, boolean given, called in /var/www/html/plugins/SmartLife/core/class/SmartLife.class.php on line 416
`

je vois ce log aussi a l'allumage si ca peut aider..  

`2019-11-19 00:04:31 | SmartLife | Erreur exécution de la commande [bureau][ruban led ][Allumer] : Param was not an HSL array
`
Si quelqu'un a une idée.. merci  :)

**Comment by sabinus52** [comment]
Pour le cas 1, il faudrait refaire une `Découverte des objets`
Pour le cas 2, certaines lampes posent apparemment problème. Comme je n'ai pas ce type de lampe, je n'ai pas pu voir ce type de problème. Je vais voir si je peux le régler.

**Comment by ytorres** [comment]
J'ai la même erreur émise sur un bandeau de led acheté chez Action :

_Param was not an HSL array_

@sabinus52 : j'ai quelques notions de développement. Guide moi pour te donner les éléments nécessaires pour déboguer ce ruban
