### ISSUE TITLE
500 : Internal Server Error

### ISSUE THREAD

**Issue by Asfalt-FR** [sabinus52/jeedom-smartlife#19]
Bonjour,
Tout d'abord merci beaucoup pour ton travail.
Il me sera très utile des que j'arriverais a connecter mon compte.
J'ai renseigner comme l'indique la documentation 
Utilisateur/Téléphone : j'ai tester le mail et le numero de tel avec 0 sans 0
Mot de passe : password (je suis sur du password j'ai meme reset au cas ou)
Code pays : 33
Plateforme/Application : SmartLife mais j'ai tester les 2 au cas ou.

J'ai toujours la même erreur :  500 : Internal Server Error
Les logs en mode debug ne changent rien : 
[2019-12-04 01:23:51][DEBUG] : CHECK CONNECTION : Start
[2019-12-04 01:23:51][DEBUG] : CONNECTION : 06xxxxxxxx (33) smart_life

Je suis sur Jeedom Raspberry Pi, derniere version a cette heure.
J'ai réinstallé le plugin.
Pourrais tu m'aider ?

**Comment by sabinus52** [comment]
Bonjour,
Il faudrait essayer avec les commandes depuis ton Raspberry que j'ai indiqué ici https://github.com/sabinus52/jeedom-smartlife/issues/2#issuecomment-544270422

**Comment by laude67** [comment]
bonjour,
c'est ok avec la commande curl

HTTP/1.1 200 OK
Date: Sat, 07 Dec 2019 11:11:09 GMT
Content-Type: application/json;charset=ISO-8859-1
Content-Length: 146
Connection: keep-alive
Server: Apache-Coyote/1.1

{"access_token":"EUheu1575217588006gZgBneF98ksltDO","refresh_token":"EUheu1575217588006gZgBn1fqTtsjS1m","token_type":"bearer","expires_in":864000}

par contre, toujours "infernal server error" avec jeedom

Laurent

**Comment by laude67** [comment]
bonjour,
je me permet de revenir vers vous concernant cette anomalie.
tout comme Asfalt-FR, je suis sur Jeedom Raspberry Pi, derniere version (3.3.39).
J'ai essayé de réinstaller le plugin et j'ai toujours l'anomalie.
J'ai tenté la commande "curl" depuis le raspberry et j'obtiens bien : {"access_token":"EUheu1575217588006gZgBn5rTvQJit7U","refresh_token":"EUheu1575217588006gZgBneje5bwNh9D","token_type":"bearer","expires_in":864000}

Pourriez vous m'aider a résoudre ce problème ?
Merci d'avance,
Laurent

**Comment by laude67** [comment]
re-bonjour,
en regardant http.error, j'ai identifié ce message : 
[Mon Dec 09 23:03:31.025574 2019] [:error] [pid 27300] [client 192.168.1.17:61076] PHP Parse error:  syntax error, unexpected 'SWITCH' (T_SWITCH), expecting identifier (T_STRING) in /var/www/html/plugins/SmartLife/vendor/sabinus52/tuyacloudapi/src/Device/DeviceFactory.php on line 20, referer: http://192.168.$

es ce que cela peut vous aider ?
Merci d'avance,
Laurent

**Comment by laude67** [comment]
J'ai réussi a m'en sortir en modifiant : 
fichier DeviceFactory.php : tous les SWITCH en TSWITCH
fichier Device.php : suppression des ": string" pour les fonctions getId(), getType(),getName(),getIcon().
tout fonctionne à merveille.
je vais creuser coté version php de mon raspberry. Je dois pas être a jour.
Bonne soirée,
Laurent

**Comment by sabinus52** [comment]
C'est la bonne correction.
Ticket déjà ouvert sur le même sujet #10 
La correction a été déjà apportée mais pas encore publiée. Je finalise une autre correction avant la publication dans une nouvelle release.

**Comment by tiangao88** [comment]
J'ai le meme souci de internal server error au niveau de Jeedom.

En essayant la commande CURL pour SmartLife j'obtiens en retour de l'authentification réussie : curl: (6) Could not resolve host: px1.tuyaus.com

Si je mets un mauvais login/mot de passe j'obtiens bien: {"responseStatus":"error","errorMsg":"Get accesstoken failed. Username or password error!"}

Mon système tourne sur un NUC: Linux Jeedom 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux
