### ISSUE TITLE
Could not resolve host: px1.tuya.com

### ISSUE THREAD

**Issue by Gregory-Hepicloud** [sabinus52/jeedom-smartlife#2]
Salut je veux test le plugin pour pouvoir dev plus tard mais j'ai ça : 

cURL error 6: Could not resolve host: px1.tuya.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Je trouve pas de serveur tuya !

**Comment by GitDev28** [comment]
Bonjour, meme problème pour moi. Quand je fais le test de connexion, j'ai cette meme erreur. Pour info, je suis aux US, je ne sais pas si ca change quelque chose mais j'ai vu qu'il fallait ajouter un identifiant pays ...

**Comment by sabinus52** [comment]
Bonjour

Est ce que cette erreur réapparait suite à la version 0.2 ?
Apparait elle rarement ou répétée ?

**Comment by scorpio686** [comment]
Salut, j'avais le même souci jusqu'à la dernière mise à jour, depuis ça fonctionne parfaitement. Merci pour le plugin ❤

**Comment by GitDev28** [comment]
J'ai installé la version via github (d47fe830bb7269e2fa880ea77336e90566920f43). Pour moi, j'ai toujours le souci et ca arrive systématiquement lors du test de connexion alors j'ai remplacé l'URL (const BASE_URL_FORMAT = 'https://px1.tuya%s.com';) dans <jeedom-smartlife/vendor/sabinus52/tuyacloudapi/src/Session/Platform.php> par https://openapi.tuyaus.com, du coup le test fonctionne mais lors de la découverte, je n'ai rien.

**Comment by GitDev28** [comment]
Est-ce que c'est parce que j'ai des smart plug que c'est pas découvert ? Je viens de penser a ca en me disant que tu étais en train de développer pour un autre type de smart device.

**Comment by sabinus52** [comment]
Avec l'url openapi.tuyaus.com fonctionne avec l'authentification mais n'est plus compatible avec toutes les autres fonctions. Il faut bien utilisé l'url px1.tuyaus.com dans ton cas.

Pour analyser ton problème, il faudrait lancer la commande Curl depuis ta box jeedom

Avec une utilisation de l'application Smartlife
~~~
curl -X POST -k -H 'Content-Type: application/x-www-form-urlencoded' -i 'https://px1.tuyaus.com/homeassistant/auth.do' --data 'userName=LOGIN&password=PASSORD&countryCode=33&bizType=smart_life&from=tuya'
~~~

Avec une utilisation de l'application Tuya
~~~
curl -X POST -k -H 'Content-Type: application/x-www-form-urlencoded' -i 'https://px1.tuyaus.com/homeassistant/auth.do' --data 'userName=LOGIN&password=PASSORD&countryCode=33&bizType=smart_life&from=tuya'
~~~

Il faut remplacer LOGIN et PASSWORD par ton nom d'utilisateur et ton mot de passe

Tu devrait récupérer une réponse de type si cela fonctionne
> {"access_token":"EUheu15446X6245Y31WxJAC5HRxarNDgj","refresh_token":"EUheu15446062XY731WxJAhCRkP8zBQ7b","token_type":"bearer","expires_in":864000}

**Comment by GitDev28** [comment]
Bonjour Olivier, 
Effectivement, ca marche bien avec le cas d'utilisation "application SmartLife", je récupère bien l'access token. J'ai donc re-modifié dans l'autre sens en supprimant le "%s" et en le remplaçant directement par "us" (i.e. "const BASE_URL_FORMAT = 'https://px1.tuyaus.com';"). Le test server fonctionne bien et dans jeedom, je récupère bien mes 2 smart plug avec leur nom et une espèce d'identifiant hexa.
Avec le "%s", ca ne fonctionne pas pour moi.
Merci en tout cas pour le message, ca m'a bien aider.
Fais moi signe si tu as besoin d'autre infos.

**Comment by GitDev28** [comment]
Je ne suis pas developer (quelques connaissances en C/C++ il y a très longtemps) mais j'ai jete un oeil sur ton code pour essayer de comprendre.

Dans Platform.php, tu devrais faire un default pour ton switch pour obtenir un code erreur peut être plus parlant. J'ai ajoute mon cas également => 'AZ' = 'US' (voir ci-après).

Mon token ressemble a ca: **AZ**haz1442012525134sBYklUycv53Yuy.

```
switch ($prefix) {
            case 'AY' : $this->region = self::CN; break;
            case 'AZ' : $this->region = self::US; break;
            case 'EU' : $this->region = self::EU; break;
            case 'US' : $this->region = self::US; break;
            default: $this->region = self::US; break;
}
```

Avec mon VPN, J'ai essayé plusieurs pays en Europe et en Amérique du Nord (en mettant un code 33) mais ca me retourne encore AZ donc ca doit être lié au compte.

**Comment by sabinus52** [comment]
Merci pour ton test.
Effectivement dans le token, Tuya renvoie sur les 2 premières caractères du token, le code de la région. Ce code permet de sélectionner le serveur tuya (asie, europe ou amérique). Normalement il doit retourner que 3 codes (AY, EU ou US). Ce code est bien lié à ton compte et tu as un code que je n'ai pas prévu ou a été ajouté par Tuya entre temps.
Je vais donc corriger et ajouter un default comme tu l'as si bien indiqué.
En attendant tu peux conserver la remplacement de `%s` par `us` dans `Plateforme.php`

**Comment by sabinus52** [comment]
La correction est dispo sur Jeedom

**Comment by laude67** [comment]
bonjour,
le token est ok par la commande cure

HTTP/1.1 200 OK
Date: Sat, 07 Dec 2019 11:11:09 GMT
Content-Type: application/json;charset=ISO-8859-1
Content-Length: 146
Connection: keep-alive
Server: Apache-Coyote/1.1

{"access_token":"EUheu1575217588006gZgBneF98ksltDO","refresh_token":"EUheu1575217588006gZgBn1fqTtsjS1m","token_type":"bearer","expires_in":864000}
