### ISSUE TITLE
Erreur "Param was not an HSL array"

### ISSUE THREAD

**Issue by reyur** [sabinus52/jeedom-smartlife#20]
Hello,

A chaque action envoyée (allumer, éteindre...), cela génère l'erreur "Param was not an HSL array".
Pourtant, tout fonctionne correctement.

Le problème est dans le fichier Color.php :

```
    public static function hslToHex( $hsl = array() ){
         // Make sure it's HSL
        if(empty($hsl) || !isset($hsl["H"]) || !isset($hsl["S"]) || !isset($hsl["L"]) ) {
            throw new Exception("Param was not an HSL array");
        }
```

En commentant ce bloc, tout fonctionne normalement.
Quel peut être le problème ?

Merci d'avance.

**Comment by sabinus52** [comment]
Bonjour,

L'erreur ne vient pas de ce code, mais depuis le 17 décembre 2019, le Cloud Tuya ne retourne plus le statut de la couleur pour les ampoules d’où l’erreur : `Param was not an HSL array` (#21). C’est peut être un problème temporaire chez Tuya, j’ai donc désactivé la mise à jour de ce statut dans Jeedom pour éviter les erreurs.
Peut être que les infos de la couleur de l'ampoule seront retournées par le Cloud Tuya plus tard. En attendant, c'est génant, mais on peut toujours changer la couleur de l'ampoule.

**Comment by reyur** [comment]
Merci pour le retour rapide.
Je comprends bien que le problème ne vient pas du code, mais depuis que j'ai commenté le "throw new Exception", je ne suis plus embêté, et tout fonctionne très bien.
En attendant de trouver mieux (ou que Tuya corrige), ça évite de polluer les logs :).

En tout cas, bravo pour le plugin!
