### ISSUE TITLE
SmartLife	Erreur exécution de la commande [Salon][LED Applique][Eteindre] : Param was not an HSL array

### ISSUE THREAD

**Issue by Richou62** [sabinus52/jeedom-smartlife#21]
Bonjour,
Le plugin est vraiment top avec une facilité d'installation et d'utilisation / Bravo….
Bémol : J'ai pu déclaré environ une dizaine d'ampoules RGB. Cela a fonctionné parfaitement et depuis j'ai ce message d'erreur à chaque commande et quelque soit la marque de l'ampoule.
Pensez vous prochainement apporter une correction au plugin?
J'ai posté ce même message sur Jeedom Community.
Encore bravo pour ce développement
Cdt

Richard

**Comment by sabinus52** [comment]
Bonjour,

Merci pour vos encouragements.
Voir la réponse et suivi dans la demande #20

**Comment by Richou62** [comment]
Merci pour votre réactivité.
La MAJ sera dispo prochainement ?

Bonnes fêtes

Richard

Koziel Richard
📭. r.koziel@outlook.com
Koziel.richard@gmail.com
☎️. +336 46 764 054
________________________________
De : Sabinus52 <notifications@github.com>
Envoyé : Saturday, December 21, 2019 6:20:48 PM
À : sabinus52/jeedom-smartlife <jeedom-smartlife@noreply.github.com>
Cc : Richou62 <r.koziel@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [sabinus52/jeedom-smartlife] SmartLife Erreur exécution de la commande [Salon][LED Applique][Eteindre] : Param was not an HSL array (#21)


Bonjour,

Merci pour vos encouragements.
Voir la réponse et suivi dans la demande #20<https://github.com/sabinus52/jeedom-smartlife/issues/20>
