### ISSUE TITLE
Problème couleur avec projecteur extérieur Novostella et Lampe de Chevet LE LampUX

### ISSUE THREAD

**Issue by JeedHome44** [sabinus52/jeedom-smartlife#22]
Bonjour,

Je t'ai contacté par le nouveau forum Jeedom pour t'envoyer les log de mes projecteurs.
Ils réagissent quand je demande une couleur en basculant dans le mode couleur mais la couleur est celle de la dernière fois que je les ai mis en mode couleur. J'ai beau en demander une autre, ca ne marche pas. J'ai regardé aussi sur l'App Smartlife en cliquant sur jeedom, le brightness se met à 3500%...
Il doit donc y avoir quelque chose sur ce type d'objet qui est un peu différent d'un simple ampoule.
Je peux te fournir toutes les infos dont tu auras besoin pour régler ce problème de couleur.

Bon réveillon à tous!

**Comment by adetauriac** [comment]
Bonjour

   Mes meilleurs vœux pour cette nouvelle année.  

 J'ai découvert ce excellent plugin avec l'achat des mêmes projecteur.s Après quelques problèmes d’identification (le mot de passe avec caractères spéciaux ne passe pas), j'obtiens le même problème, impossible de gérer la couleur, ça positionne par défaut la dernière valeur enregistré par l'application.

 Je n'ai que cet appareil pour tester donc je peux pas vérifier.

 Merci

**Comment by JeedHome44** [comment]
Ca veut donc dire que le problème vient bien du plugin alors.
Avec ce type d'éclairage, il doit y avoir quelque chose en plus à faire je pense avant de pouvoir changer de couleur.
Sur l'App smartlife, ce n'est pas le même menu je pense qu'une ampoule classique. Quand on clique sur le bouton On/Off en bas, il y a 3 onglets qui apparaissent en haut. White/Colors/Scene
Si ca peut aider à résoudre le problème! :)

**Comment by sabinus52** [comment]
Depuis fin décembre, il n'y a plus moyen de récupérer la couleur via le cloud Tuya. Tuya ne retourne plus cette valeur. Une partie du problème peut venir de là.
Pour le reste, ne possédant cet équipement et qu'il est, semble-t-il différent d'une ampoule, je me sera difficile d'apporter des modifications pour le rendre compatible.
