### ISSUE TITLE
Doorbell SmartLife video

### ISSUE THREAD

**Issue by JeedHome44** [sabinus52/jeedom-smartlife#23]
Bonjour,

Est-ce possible de rendre compatible Jeedom les sonnettes video SmartLife/Tuya?
Ou alors, sur SmartLife, on peut faire une automatisation vers le centre Message.
Ce centre message peut il servir de déclencheur sur Jeedom grâce au plugin?

Merci

**Comment by sabinus52** [comment]
Bonjour,
Le plugin n'est compatible qu'avec les objets que l'on peut contrôler avec un assistant vocal.
Comme il n'est pas possible d'avoir des états en temps réel, ce produit ne pourra pas pris en compte.
Désolé.
