### ISSUE TITLE
Aucun appareil lors de la détection

### ISSUE THREAD

**Issue by bet02** [sabinus52/jeedom-smartlife#24]
Bonjour, j'ai le même problème lors de la détection, il ne découvre aucun appareil. De plus, lorsque je fais le test de connection, on dirait qu'il n'est pas constant, qu'il fonctionne de temps a autre.
Je ne suis pas un programmeur et je tente d'intégrer dans un outil mes différents appareil.
J'inclus le fichier en mode débug

Merci
[SmartLife.txt](https://github.com/sabinus52/jeedom-smartlife/files/4091071/SmartLife.txt)

Tony

**Comment by sabinus52** [comment]
Bonjour,

D'après le log, tout fonctionne parfaitement et tuya bien retourne 0 device. C'est quoi comme type d'équipement ?
Si ceux ne sont pas des ampoules ou des prises connectées, c'est normal.

**Comment by bet02** [comment]
Bonjour, merci pour votre réponse,
Oui, il y a des prises connectés dans mes appareils.
Lorsque je demande de faire la connection avec Tuya, j'ai souvent un
message indiquant 500: internal error,est-ce que cela pourrait être pour
cette raison que la reconnaissance fonctionne mal??
De plus, est-ce qu'il y a une liste spécifique de fabricant que Tuya
reconnait?
Dernière question, est-ce qu'éventuellement, il pourrait reconnaître
l'ensemble des appareil que l'Application reconnait?
Je suis vraiment novice dans le domaine, alors pardonnez-moi à l'avance si
mes questions peuvent paraître un peu simplet :)

merci encore et bonne journée

Tony

Le ven. 24 janv. 2020, à 13 h 30, Sabinus52 <notifications@github.com> a
écrit :

**Comment by sabinus52** [comment]
Le problème est probablement le même que l'issue #11.
La liste des équipements reconnus par le plugin est indiqué dans la documentation du plugin

**Comment by bet02** [comment]
Bonjour, j'ai fait la nouvelle mise a jour du plugin ce matin, et tout a
fonctionné.

Merci encore pour votre aide, c'est très apprécié:)

Bonne journée

Tony

Le sam. 25 janv. 2020, à 08 h 42, Sabinus52 <notifications@github.com> a
écrit :
