### ISSUE TITLE
Problème de pourcentage.

### ISSUE THREAD

**Issue by falimero** [sabinus52/jeedom-smartlife#26]
J'ai ajouter des lumières, mais slider de luminosité ne fonctionne pas correctement. Jai une différence entre le slider et l'application smartphone.

exemple : quand je met sur le slider a 100% => ca allume bien a 100%. 
quand j'allume a 49% (slider ) => ca allume a 43% (appli)
quand j'allume a 11% (slider ) => ca allume a 2% (appli)

**Comment by sabinus52** [comment]
C'est tout a fait normal. C'est une chose que j'ai aussi remarquée. 
Ce décalage est voulu pour avoir une compatibilité avec le maximum de lampes.

**Comment by falimero** [comment]
> C'est tout a fait normal. C'est une chose que j'ai aussi remarquée.

C'est pas normal non :)
