### ISSUE TITLE
Jeedom Konyks

### ISSUE THREAD

**Issue by synthol67** [sabinus52/jeedom-smartlife#29]
Bonjour,
J'ai téléchargé le plugin Smartlife sur jeedom. Seulement, je n'arrive pas à me connecter sur mon compte Konyks. Problème d'authentification : Identifiant ou mot de passe inconnu. Je me suis inscrit chez konyks via leur app et pas celle de Smartlife ou Tuya. Pour tester, j'ai crée un compte via l'app smartlife. Là j'arrive à me connecter sur le compte créer sauf que j'ai mes prises priska+ et polyco sur mon compte konyks. Comment peut-on se connecter sur le compte Konyks ? Le service sera arrêté très bientôt sur IFTTT !!!
Cordialement
J'ai un RPI 3B avec Jeedom 3.3.49 et Debian Stretch

**Comment by sabinus52** [comment]
Bonjour,
Le plugin n'est pas compatible avec Konyks. Il faut utiliser soit l'appli Tuya ou soit l'appli SmartLife.
Les objets dans l'appli Konyks sont liés uniquement à cette appli.
Il faut donc y enregistrer à nouveau tous ses équipements dans la nouvelle appli choisie (Tuya ou SmartLife)

**Comment by synthol67** [comment]
Merci. Je les ai inclus avec l'App tuyau et ça marche. Bon weekend
