### ISSUE TITLE
Utilisation

### ISSUE THREAD

**Issue by HerveKr** [sabinus52/jeedom-smartlife#3]
Super projet ! Merci ! 
Installé sur mes 7 Multiprises ,
Fonctionne quasi correctement ,
Parfois il n'arrive pas joindre l'Api et cela crée une erreur (Curl error 28).

Ces pb étant souvent temporaires ...

**Comment by HerveKr** [comment]
Je retire : 
N'arrive pas à joindre ... 
En fait je suis entrain de faire des travaux chez moi, et la multiprise était .... déconnectée . 
Pffft 
Toutes mes excuses

**Comment by sabinus52** [comment]
Merci !
Mais j'ai remarqué aussi que très rarement, les serveurs Tuya ne retournent pas de réponse.
Je vais rajouter un test  que si en cas d’échec de retenter de nouvel essai de la requête.

**Comment by HerveKr** [comment]
Oui ! c'est un peu aléatoire , le serveur Tuya qui ne répond pas ...
Mais bonne idée, si tu peux le faire , suis preneur !

Merci,

**Comment by HerveKr** [comment]
Pour Info les Prises Wifi BlitzWolf de Banggood fonctionnent avec Tuya, et l'appli Smart Life ... et fonctionnent aussi donc avec le plugin !
En Promo 👍 https://www.banggood.com/BlitzWolf-BW-SHP6-EU-Plug-Metering-Version-WIFI-Smart-Socket-220V-240V-10A-Work-with-Amazon-Alexa-p-1356981.html?cur_warehouse=CN
