### ISSUE TITLE
Autres types d'appareils

### ISSUE THREAD

**Issue by JeedHome44** [sabinus52/jeedom-smartlife#30]
Bonjour,

Le plugin n'est plus mis à jour depuis un moment.
Pouvez vous ajouter d'autres types d'appareils?

Caméra, aspirateur...

Merci

**Comment by sabinus52** [comment]
Merci de se reporter à la documentation https://sabinus52.github.io/jeedom-smartlife/ pour connaitre la faisabilité d'intégrer de nouveaux appareils
