### ISSUE TITLE
Intégration climatiseur Qlima

### ISSUE THREAD

**Issue by chris94440** [sabinus52/jeedom-smartlife#32]
Bonjour
J’ai intégré dans mon smartlife un climatiseur Qlima … il est totalement fonctionnel au travers de l’ap android … j’ai donc synchronisé mon app jeedom pour espérer récupérer cet équipement meme si tu as précisé les périphériques pris en charges … tant qu’il y a de l’espoir y a de la vie … :slightly_smiling_face:

Logs suite découverte des objets jointe à l'issue
[SmartLife.txt](https://github.com/sabinus52/jeedom-smartlife/files/4740181/SmartLife.txt)

Détail log objet non reconnu : 
 [2020-06-06 16:18:20][DEBUG] : SEARCH DEVICE : Objet non pris en compte Sabinus\TuyaCloudApi\Device\UnknownDevice Object (     [devType:protected] => climate     [id:protected] => 01106740cc50e350ad0c     [type:protected] => unknown     [name:protected] => Clim chambre Clement     [icon:protected] => https://images.tuyaeu.com/smart/icon/1493368574_0.png     [data:protected] => Array         (             [min_temper] => 55             [temperature] => 55             [max_temper] => 90             [online] => 1             [state] => false             [temp_unit] => FAHRENHEIT         )  ) 

Marque et modèle du climatiseur : 
Qlima P528 wifi 
lien constructeur : https://www.qlima.fr/gamme/climatisation/climatiseurs-mobiles/p528/
Perso je l'ai acheté chez Leroy Merlin

Caractéristiques : 
- on / off
- monter / descendre température (min : 18 | max : 32)
- vitesse de ventilation (auto / low / med / high)
- mode (dry / cool / fan)
- function (sleep/swing/fahrenheit / celsius)
  il s'agit d'options unitaire sauf fahrenheit ou celsius ... qui sont soit l'une soit l'autre
- function timer 

Hésites pas si tu as des questions ou si tu veux que je test..:-)
Par avance merci
Christophe

**Comment by Shadarus** [comment]
Juste pour info si tu veux tester, j'ai également la même clim  (P528 achetée en 2019)

à l'époque j'avais utilisé un script qui utilisait l'API tuya, j'avais récupéré ID et Key avec l'app tuya paramétrée et tout ça pour rien vu que ne l'ayant pas utilisé depuis un an ça a tout supprimé (je pense?) car plus de clim qui apparaissait dans TUYA, alors j'ai recréé mon compte dans l'appli Smarthome + nouvelle inclusion de la clim
en résumé testeur de plus prêt pour le départ :smile:

**Comment by slayer-fr** [comment]
hello , vous avez réussi a faire marcher cette clim sous jeedom ?

**Comment by chris94440** [comment]
Hello
Oui mais pas avec le plugin smartlife...
Cordialement
Christophe Demongeot

Envoyé de mon Samsung Galaxy S10 Orange
Téléchargez Outlook pour Android<https://aka.ms/ghei36>
________________________________
