### ISSUE TITLE
intégration  Interrupteur WiFi 

### ISSUE THREAD

**Issue by rudak** [sabinus52/jeedom-smartlife#34]
salut

j'ai ce type de relais qui marche assez bien mais il n'est pas reconnu par le plugin

![71EREp5cxKL _AC_SL1500_](https://user-images.githubusercontent.com/604478/83952807-d77c3600-a83b-11ea-8d99-77cc4cd3cfc4.jpg)

[lien amazon](https://www.amazon.fr/LoraTap-Interrupteur-Commutateur-Intelligent-Compatible/dp/B07R4W3CL1/ref=pd_bap_rp_11?_encoding=UTF8&pd_rd_i=B07R4W3CL1&pd_rd_r=3d563528-750b-4e41-83dc-c62bb95d5400&pd_rd_w=TUNph&pd_rd_wg=BrOR9&pf_rd_p=f87e0102-7629-48eb-833e-dbb77c69662a&pf_rd_r=XFD08465ZENTZ5GRSEQ1&psc=1&refRID=B4HKY3D8S0YBQ9V9YQQZ)

j'aimerai bien pouvoir t'aider a l'intégrer (ainsi que d'autres matériels éventuellement) mais je ne sais pas ce que je peux faire a mon niveau, pourrais tu m'indiquer le genre d'infos qu'il te faudrait pour y parvenir ?

**Comment by sabinus52** [comment]
Bonjour,

Je ne sais pas si c'est possible d'ajouter cet équipement.
Il faut se reporter à la documentation du plugin pour savoir si cet objet est éventuellement compatible.
Suite au retour, je pourrai dire si c'est faisable ou pas.

Cdlt

**Comment by pouda** [comment]
Bonjour, j'ai ce module aussi et la découverte automatique du plugin ne me le trouve pas ..

C'est un peu dommage car je pense que nous sommes plusieurs à avoir le soucis... me dire si je peux aider ?? sinon, si il ny'a aucune chance d'intégration je verrais pour le remplacement par un module Sonoff ... mais bon, ca fait toujours un peu chier de remplacer des choses qui fonctionnent encore et plutot bien :) 

Merci de ton retour, bye.

**Comment by Daar59** [comment]
Bonjour, 

Je me retrouve avec le même soucis... en creusant un peu, je me suis rendu compte que cet équipement n'est même pas retourné par le discoverDevices(). Pour moi il serait compatible, c'est juste un switch On/Off.

Merci à vous !

**Comment by sabinus52** [comment]
Si l'équipement ne remonte pas durant la découverte, cela veut dire qu'il n'est pas compatible avec le plugin.
