### ISSUE TITLE
Message d'erreur Volets 

### ISSUE THREAD

**Issue by HerveKr** [sabinus52/jeedom-smartlife#35]
Bonjour, Sabinus ! 
Et encore Merci pour ce Plugin ! 

Je viens ici juste t'informer d'une erreur qui est apparue il y a 2 ou 3 jrs ... 

Sans changement de mes scenarios : 
Qd le scenario fonctionne j'ai les erreurs suivantes : 

Message: Erreur de connexion au cloud Tuya : Argument 1 passed to Sabinus\TuyaCloudApi\Device\Device::setData() must be of the type array, null given, called in /var/www/html/plugins/SmartLife/vendor/sabinus52/tuyacloudapi/src/Device/Device.php on line 145

Message: Erreur exécution de la commande [Living Bis][Volet Living Fenêtres][Stopper] : Erreur de connexion au cloud Tuya : Argument 1 passed to Sabinus\TuyaCloudApi\Device\Device::setData() must be of the type array, null given, called in /var/www/html/plugins/SmartLife/vendor/sabinus52/tuyacloudapi/src/Device/Device.php on line 145

Comme je ne sais pas si tu lis le forum (me semble que tu préférais ici) 
je te poste le pb ici 

Sommes plusieurs avec ce souci 
Lien dans le forum : 
https://community.jeedom.com/t/erreur-de-connexion-au-cloud-tuya/31204

Merci !
Bon Week end,

Hervé

**Comment by sabinus52** [comment]
Merci pour ton retour et tes différents tests depuis le forum Jeedom
