### ISSUE TITLE
Ajout device SINOTIMER TM609 

### ISSUE THREAD

**Issue by Richou62** [sabinus52/jeedom-smartlife#36]
Bonjour,
Bravo pour ce plugin. 
Est-il possible d'ajouter le telerupteur  Wifi Sinotimer TM609 à la norme DIN Rail ?
Ce Device peut remplacer n'importe quel telerupteur existant, à condition d'avoir la couverture Wifi naturellement. C'est un vrai plus.

Gros avantages : On  conserve le fonctionnement habituel des interrupteurs existants et on ajoute la gestion dans Jeedom grace au plugin Tuya Smarlife.

Merci encore pour ce plugin

Bonne continuation 

Cordialement 

Richard

**Comment by sabinus52** [comment]
Bonjour,

Je ne sais pas si c'est possible d'ajouter cet équipement.
Il faut se reporter à la documentation du plugin pour savoir si cet objet est éventuellement compatible.
Suite au retour, je pourrai dire si c'est faisable ou pas.

Cdlt

**Comment by Richou62** [comment]
Bonjour,

Dans la documentation du plugin, les objets suivants sont compatibles :

Prises connectées
Scènes
Interrupteurs pour volets roulants
Ampoules connectées

J'ai reussi à gérer mon telerupteur en utilisant le thème "Scenes" de tuya en créant dans l'application Tuya 2 scénarios pour commander le telerupteur ( on, off).
J'ai retrouvé ces 2 scenarios dans le plugin Tuya de Jeedom ( Scenes).
Chaque objet créé a une seule commande : activer.

J'ai ensuite créé un virtuel  interrupteur lumière  pour commander le telerupteur et cela fonctionne parfaitement.

En revanche, si le plugin pouvait reconnaître directement l'objet, cela éviterait tous ces intermédiaires pour y parvenir.

Ceci dit, merci Jeedom, car, on a toujours une solution pour s'en sortir  et merci à vous pour ce plugin qui change la vie des objets connectés.

Cdt

Richard

Koziel Richard
📭. r.koziel@outlook.com
Koziel.richard@gmail.com
☎️. +336 46 764 054
________________________________
De : Sabinus52 <notifications@github.com>
Envoyé : Saturday, July 4, 2020 5:51:34 PM
À : sabinus52/jeedom-smartlife <jeedom-smartlife@noreply.github.com>
Cc : Richou62 <r.koziel@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [sabinus52/jeedom-smartlife] Ajout device SINOTIMER TM609 (#36)


Bonjour,

Je ne sais pas si c'est possible d'ajouter cet équipement.
Il faut se reporter à la documentation du plugin pour savoir si cet objet est éventuellement compatible.
Suite au retour, je pourrai dire si c'est faisable ou pas.

Cdlt
