### ISSUE TITLE
Climatiseur CLATRONIC

### ISSUE THREAD

**Issue by Yasu888** [sabinus52/jeedom-smartlife#37]
Bonjour Sabinus52,

Les beaux jours arrives et donc j'ai décidé de prendre un climatiseur, par chance celui-ci utilise SmartLife pour fonctionner.
Étant sur Jeedom, il me semblais bien avoir vu ton plugin qui portais le nom de l'application.

Sans plus apprendre, j'installe ton plugin, lis la documentation et lance la découverte sans grand espoir car je vois que les Clims ne sont pas pris par défaut.

Mais je vois que tu es en mesure de rajouter si dans le mode debug cela remonte, et regarde mes log et la bingo, tout espoir n'est pas perdu.
Voici ce que j'obtiens :

`[DEBUG] : SEARCH DEVICE : Objet non pris en compte Sabinus\TuyaCloudApi\Device\UnknownDevice Object (     [devType:protected] => climate     [id:protected] => 75830402f4cfa24f4b76     [type:protected] => unknown     [name:protected] => Climatiseur CLATRONIC     [icon:protected] => https://images.tuyaeu.com/smart/product_icon/kt.png     [data:protected] => Array ([mode] => cold  [current_temperature] => 22 [min_temper] => 16 [temperature] => 22 [max_temper] => 31             [online] => 1 [state] => false  [support_mode] => Array( [0] => cold  [1] => hot  [2] => wind  [3] => auto)  [temp_unit] => CELSIUS)  )`

Serait-il possible dans tes prochaine mise à jour de rajouter ce climatiseur STP ?

N'hésite pas si il te faut d'autres infos
Merci par avance

**Comment by sabinus52** [comment]
Bonjour,

J'ai déjà une demande en cours #32 pour l'intégration d'un climatiseur.
Mais je vois que le retour du Cloud Tuya pour ce climatiseur comporte plus de données que celui du #32, ceux qui me permettra de compléter mon dev et d'avoir des retours différents.
Peux tu me donner plus d'infos comme cela a été fait dans la demande #32.

Merci

**Comment by Yasu888** [comment]
Bonjour Sabinus52,

Voici les informations qui te permettrons de comprendre mon Climatiseur.

![image](https://user-images.githubusercontent.com/65353147/86827906-dafd1a00-c092-11ea-99a1-a1766c023a85.png)

En espérant que cela puisse t'aider
Bien cordialement

**Comment by sabinus52** [comment]
Bonjour,

Merci pour ces infos.
Quel est le nom du modèle exact du climatiseur ?

Tu peux me contacter en MP sur https://community.jeedom.com/ pour que je te communique un lien pour télécharger les sources adaptées à ton climatiseur et faire des tests.

**Comment by Yasu888** [comment]
Bonjour,
Mon modèle est le climatiseur Clatronic CL 3716

**Comment by Yasu888** [comment]
Bonsoir Sabinus52,
Je me permet de te recontacter, car j'ai essayé de le faire par
community.jeedom.com comme demandé.
Ayant eu mes vacances entre temps et sûrement les tiennes aussi, je voulais
savoir quoi faire pour d'aider à tester.
Bien cordialement

Le sam. 25 juil. 2020 à 19:06, Sabinus52 <notifications@github.com> a
écrit :

**Comment by sabinus52** [comment]
J'ai envoyé depuis community.jeedom.com, le lien de téléchargement pour les tests

**Comment by Yasu888** [comment]
Bonjour Sabinus52,
Merci pour le script.
J'ai pu le lancer et je t'ai fait son retour sur community.jeedom.com.
Aucunes erreurs constatées.
Merci encore pour tes efforts afin d'agrandir les équipements compatible avec ton plugin. :)
Bien cordialement
