### ISSUE TITLE
Détecteur de porte

### ISSUE THREAD

**Issue by Bockelbam** [sabinus52/jeedom-smartlife#38]
Bonjour,
J'ai des détecteurs d'ouverture de porte que j'ai dans Smartlife, mais qui ne remontent pas dans jeedom
Comme j'ai un scénario dans smartlife qui me permet de lancer une alarme lors de l'ouverture d'une des portes, je comptais également pouvoir le faire dans jeedom.

Je viens de m'apercevoir également que ma petite caméra tuya ne remonte pas également.

Si vous avez besoin de plus d'info ...

**Comment by sabinus52** [comment]
Bonjour,

Comme indiqué dans la documentation, ce type d'objet (alarme, détecteur, camera) ne sont pas pris en charge par le plugin.
Pour trouver une alternative, il est préférable de poser la question sur le forum de Jeedom.

Cdlt
