### ISSUE TITLE
Remontée conso jeedom pour prise wifi neocoolcam

### ISSUE THREAD

**Issue by bricolgloo** [sabinus52/jeedom-smartlife#4]
Bonjour, 

tout d'abord merci pour ce plugin :)
je viens vers toi car j'ai acquis recemment une prise neocoolcam wifi (qui fonctionne parfaitement a travers ton plugin)
mais je n'arrive pas a avoir les relevés de conso sur Jeedom ... ca n'est pas bloquant mais ca serait un gros plus !

Est ce que tu n'a pas intégré ces données par manque d'info ou une autre raison ? Si c'est par manque d'infos, n'hésites pas a me solliciter pour que je te donnes des trames ou log ou un acces a mon compte cloud smartlife pour que tu puisses t'y retrouver , et retrouver les infos de consos liées :) 

Et si ca peux te motiver, je suis pret a mettre une petite somme pour participer a ton dev (j'ai une maigre bourse mais je peux participer a hauteur de 5€ sans soucis :) )

Je t'ai envoyé la meme demande via mail depuis le forum Jeedom :)

Merci de m'avoir lu et bonne soirée !

**Comment by sabinus52** [comment]
Bonjour,
En plus de la réponse par mail, je complète pour indiquer que le Cloud API des serveurs Tuya ne retourne malheureusement pas ce type d'information pour ces prises connectées avec relevé de conso.
