### ISSUE TITLE
Intégration climatiseur portable Wood's Cortina silent 12k smarthome

### ISSUE THREAD

**Issue by Aspect-Geek** [sabinus52/jeedom-smartlife#41]
Bonjour,

Tout d'abord merci pour le développement et la mise à disposition du plugin 👍 

Suivant la doc, après intégration du climatiseur mobile Wood's Cortina silent 12k smarthome dans l'application Tuya et tentative de synchronisation dans le plugin, voici la ligne de log : 

`[2020-08-24 17:26:07][DEBUG] : SEARCH DEVICE : Objet non pris en compte Sabinus\TuyaCloudApi\Device\UnknownDevice Object (     [devType:protected] => climate     [id:protected] => xyxyxyxyxyxy     [type:protected] => unknown     [name:protected] => Clim Mobile     [icon:protected] => https://images.tuyaeu.com/smart/program_category_icon/kt.png     [data:protected] => Array         (             [current_temperature] => 27             [min_temper] => 17             [temperature] => 22             [max_temper] => 30             [online] => 1             [state] => false             [temp_unit] => CELSIUS         )  )`

Serait-il possible d'inclure ce type d'équipement ?

Merci d'avance !

**Comment by sabinus52** [comment]
Bonjour,

Comme pour la demande #32 et #37, merci de me communiquer toutes les infos.
Après je fournirai un script pour faire un test de compatibilité.

Cdlt

**Comment by sabinus52** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [dzs](https://trello.com/c/pTzN5oZ9/1-dzs)

**Comment by Aspect-Geek** [comment]
Merci à toi, voici des informations concernant les fonctionnalités utilisables par l'application :

-Marche/Arrêt
-Mode de refroidissement
-Mode déshumidification
-Mode Chauffage
-Mode Ventilateur
-Mode Éco
-Réglages de la température
-Choix de la vitesse : Basse, Moyenne 
et Élevée
-Minuterie : 1-24 h
-Veille : Marche/Arrêt
-Nettoyage automatique : Marche/ 
Arrêt
-Verrouillage : Marche/Arrêt 
-Celsius/Fahrenheit
-Oscillation : Marche/Arrêt

Merci

**Comment by sabinus52** [comment]
Voici une version qui est téléchargeable ici [http://dl.free.fr/jRweHITY3](http://dl.free.fr/jRweHITY3) et qui peut être testé.
Il suffit de décompresser cette archive de préférence sur la box et d’aller dans le dossier TuyaCloudApi/test et de lancer en ligne de commande php climate.test.php [LOGIN] [PWD] [ID OBJET] .

Merci pour les tests et ton retour

**Comment by Aspect-Geek** [comment]
Je viens juste de tester, et comme j'utilise l'application Tuya et non SmartLife j'ai modifié la valeur _Platform::SMART_LIFE_ par _Platform::TUYA_ dans le fichier climate.test.php.

En lançant le script j'ai bien un retour d'état, mais une erreur lors de l'allumage du climatiseur : 

> Sabinus\TuyaCloudApi\Device\ClimateDevice Object
> (
>     [id:protected] => xyxyxyxyxy
>     [type:protected] => climate
>     [name:protected] => Clim Mobile
>     [icon:protected] => https://images.tuyaeu.com/smart/program_category_icon/kt.png
>     [data:protected] => Array
>         (
>             [current_temperature] => 25
>             [min_temper] => 17
>             [temperature] => 22
>             [max_temper] => 30
>             [online] => 1
>             [state] => false
>             [temp_unit] => CELSIUS
>         )
> 
> )
> 
> -------------------------
>  -> Allumage du climatiseur
> PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Sabinus\TuyaCloudApi\Device\ClimateDevice::turnOn(), 0 passed in /tmp/TuyaCloudApi/test/climate.test.php on line 27 and exactly 1 expected in /tmp/TuyaCloudApi/src/Device/ClimateDevice.php:194
> Stack trace:
> #0 /tmp/TuyaCloudApi/test/climate.test.php(27): Sabinus\TuyaCloudApi\Device\ClimateDevice->turnOn()
> #1 {main}
>   thrown in /tmp/TuyaCloudApi/src/Device/ClimateDevice.php on line 194

Si tu veux je peux créer un compte sur l'appli SmartLife et y inclure la clim pour tester si ça peut t'aider.
Merci à toi
