### ISSUE TITLE
Prise avec conso / BW-SHP6

### ISSUE THREAD

**Issue by LaurentP21** [sabinus52/jeedom-smartlife#42]
Bonjour,

Je viens d'acheter une prise "BlitzWolf® BW-SHP6 Pro 15A" sur Banggood.
Dans l'application Smart Life, je vois bien la consommation instantané en W (de même que les mA, le voltage, et la conso totale (je ne sais pas si c'est le total de la journée, du mois, ou général).

Dans Jeedom, pas de problème pour l'allumer / l'éteindre... mais y-aurait-il un moyen de récupérer les infos de conso ?
Voici Le log d'inclusion, mais j'imagine qu'il ne faut pas que ça...
[SmartLife.txt](https://github.com/sabinus52/jeedom-smartlife/files/5274461/SmartLife.txt)

Merci,

Laurent.

**Comment by sabinus52** [comment]
Bonjour,

Les infos de consommation ne remontent pas via le Cloud Tuya, donc impossible de les afficher dans le plugin.
Il faut passer dans ce cas en mode local et utiliser un autre plugin compatible.
