### ISSUE TITLE
Passage de Jeedom v3 à v4

### ISSUE THREAD

**Issue by JeedHome44** [sabinus52/jeedom-smartlife#43]
Bonjour,

Je suis passé de Jeedom v3 à Jeedom v4 et je m'attendais à avoir les nouvelles options du plugin Smartlife pour le timeout et le choix d'activer ou non les objets à chaque découverte.

Cependant, j'ai vérifié plusieurs fois si une mise à jour est dispo et rien...

Comment forcer le plugin à faire la mise à jour v4 pour obtenir les nouvelles options?

Merci

**Comment by sabinus52** [comment]
Bonjour,

Ce problème n'a rien à voir avec le plugin. Merci de passer le forum Jeedom pour ce type de question.
Beaucoup de personnes ont migré de la v3 et v4 et n'ont pas eu ce problème.

Il y a du avoir un problème dans le core de Jeedom pendant la migration.
Il faut essayer de désinstaller le plugin et le réinstaller
