### ISSUE TITLE
Prise avec conso / AWOW SmartPlug EU3S

### ISSUE THREAD

**Issue by Lionel-31** [sabinus52/jeedom-smartlife#46]
Bonjour 

J ai correctement connecter la prise et fonctionne sous Jeedom 
par contre la consommation n'ai pas remonté a Jeedom 

Est ce normal ? 
Y a t il une manip a faire ? 

Ou tout simplement la fonction n est pas géré ? 

Merci d'avance

**Comment by sabinus52** [comment]
Bonjour,

Les infos de consommation ne remontent pas via le Cloud Tuya, donc impossible de les afficher dans le plugin.
Il faut passer dans ce cas en mode local et utiliser un autre plugin compatible.

**Comment by Lionel-31** [comment]
Ok dommage 
Merci pour le retour -> Peux tu mettre une infos dans la doc ?
Une idee pour le plugin ?
