### ISSUE TITLE
Erreur de connexion au cloud Tuya : cURL error 60: SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by StEfDu6o** [sabinus52/jeedom-smartlife#47]
Bonjour,

J'ai ce message à chaque fois que dans mon scénario je veux utiliser mon ampoule. Quand je l'allume directement depuis le dashboard Jeedom tout fonctionne bien...

Merci de votre aide !

**Comment by sabinus52** [comment]
Bonjour,

Pourrais je avoir plus d'information et les logs qui vont avec.
Mais à première vue, cela ressemble à ce que la version du système devient obsolète (PHP, openssl, autorité de certification). Donc rien à voir directement avec le plugin.
Une réponse a été donnée sur le forum de Jeedom : https://community.jeedom.com/t/plugin-smartlife-tuya-discussion-generale/7314/218 et https://community.jeedom.com/t/plugin-smartlife-tuya-discussion-generale/7314/221

Cdlt

**Comment by StEfDu6o** [comment]
Merci,

J'ai fait une mise a jour du RPI, j'avais déjà mis a jour la liste des certificats comme présenté dans les solutions en liens. J'ai retéléchargé de nouveau le fichier nécessaire, et vérifier la manip : tout est ok mais problème toujours présent uniquement dans le scenario que j'utilise ( je me répète mais en manuel tout fonctionne bien...)

![Screenshot_2](https://user-images.githubusercontent.com/50077428/98019646-4c12cb00-1e02-11eb-9eda-9570138fcb08.png)
![Screenshot_1](https://user-images.githubusercontent.com/50077428/98019656-4fa65200-1e02-11eb-9572-f8fcdc6882ff.png)

[SmartLife.txt](https://github.com/sabinus52/jeedom-smartlife/files/5482974/SmartLife.txt)
