### ISSUE TITLE
Intégration GRDE Smart WiFi Alarm

### ISSUE THREAD

**Issue by oTiMo** [sabinus52/jeedom-smartlife#48]
J'ai fait l'acquision de ce petit réveil : GRDE Smart WiFi Alarm 

![image](https://user-images.githubusercontent.com/633957/98872642-32632a80-2477-11eb-8e6d-298a1b8d80f6.png)

Il est détecté en tant que lampe, et je peux allumer et éteindre la veilleuse sur le dessus sans problème.

Mais il a vraiment beaucoup de fonction, et j'aurais bien l'intégrer un peu mieux.

Je suis développeur Ruby mais je peux tenter de gratter en PHP via l'exemple qu'on trouve ici https://github.com/sabinus52/jeedom-smartlife/blob/master/vendor/sabinus52/tuyacloudapi/test/exemple.php

Mais je ne sais pas trop comment m'y prendre pour récupérer les commandes possibles.

Une idée ?

**Comment by sabinus52** [comment]
Bonjour,

Le seul moyen de récupérer les fonctions c'est de faire une recherche sur un Internet.
Mais comme il est détecté en tant que "lampe" il n'y aura de toute façon que les fonctions standard d'une lampe.

Malheureusement, je ne peux pas faire de plus !
