### ISSUE TITLE
Essai commande volets roulants 

### ISSUE THREAD

**Issue by HerveKr** [sabinus52/jeedom-smartlife#5]
Bonjour, je vais tenter d'utiliser ton plugin pour la commande de mes volets ! 
Avec quels interrupteurs muraux, pour volets roulants, as tu fait tes essais ? 
Plusieurs modeles 
...
Merci

Nb. : Plus AUCUN souci de mon coté avec le Plugin 
Merci

**Comment by sabinus52** [comment]
Bonjour,

J'ai testé avec ce modèle commandé sur Amazon : https://www.amazon.fr/gp/product/B07MXT9Y2D/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1
Les commandes fonctionnent, il y a juste un petit problème de retour de statut qui sera réglé très prochainement.
Au niveau des actions, on peut ouvrir, fermer et stopper le volet. Donc si tu veux fermer à moitié par exemple, il faudra faire un scénario.

**Comment by HerveKr** [comment]
Merci de ta réponse :)

**Comment by HerveKr** [comment]
Plugin Testé avec ce modele : 
https://www.amazon.fr/gp/product/B07PQ11PPS

Top ! Fonctionne correctement . 
J'ai encore du mal avec les retour d'état ... 0.1.2.3... Mais comme mon branchement est inversé pour le moment. 

Merci !!!

**Comment by sabinus52** [comment]
J'ai corrigé le problème de statut des volets roulants.
Je me suis basé sur les statuts de Jeedom :
- **0** fermé
- **1** à moitié ouvert
- **2** ouvert

**Comment by HerveKr** [comment]
Merci ! 
Je te tiens au courant si je constate un pb.
Bonne journée !
