### ISSUE TITLE
Erreur de connexion au cloud Tuya : you cannot auth exceed once in 60 seconds

### ISSUE THREAD

**Issue by PhilippeMPerso** [sabinus52/jeedom-smartlife#52]
Bonjour,

Tous les utilisateurs du plugin SmartLife dans Jeedom ont cette erreur depuis hier soir. Il semblerait que Tuya ait mis une limitation à la fréquence d'authentification...

Cordialement,
Philippe

**Comment by rudak** [comment]
pareil je confirme
![image](https://user-images.githubusercontent.com/604478/100481892-e14d6a80-30f5-11eb-9b5a-fe613e275003.png)

**Comment by sabinus52** [comment]
Bonjour,

Effectivement, depuis quelques jours, cette erreur est apparue suite à une nouvelle restriction du Cloud Tuya. Je comprends que cette erreur est peut être gênante, mais elle reste non bloquante. 
Personnellement, je ne suis pas encore tombé sur cette erreur dans Jeedom.
Pour info, si dans un scénario, on veut lancer plusieurs commandes sur différents objets Tuya, il n'y a pas le problème.

Pour contourner ce problème, il faudrait, dans ce cas, revoir entièrement le développement du plugin.

**Comment by PhilippeMPerso** [comment]
Bonsoir,
Dans mon cas, mes prises connectées sont reliées à un interrupteur Nodon. Donc quand je veux utiliser l'interrupteur, il faut juste attendre 60s pour allumer une 2ème prise connectée....ou attendre 60s pour éteindre une prise allumée par erreur. Très pénible :)
En géneral, pour utiliser un web service, il faut s'authentifier pour récupérer un token, qui a une certaine durée de vie, et l'inclure dans le header des requêtes des commandes. N'y aurait-il pas un moyen dans Jeedom de procéder de la sorte? J'ai jeté un oeil à votre code source (je ne connais pas du tout l'api de Tuya, ni le fonctionnement de Jeedom), et je sais qu'une variable statique ne peut pas être partagée entre 2 scénarios. Mais il y a peut-être un moyen de régler le problème sans tout réécrire, non?
Si l'api Tuya fonctionne avec un token, il suffirait "juste" de partager ce token entre les scénarios...
(Je vais regrouper mes interrupteurs dans le même scénario en attendant....mais le pb reste le même...)

**Comment by dixzerohuit** [comment]
> Bonjour,
> 
> Effectivement, depuis quelques jours, cette erreur est apparue suite à une nouvelle restriction du Cloud Tuya. Je comprends que cette erreur est peut être gênante, mais elle reste non bloquante.
> Personnellement, je ne suis pas encore tombé sur cette erreur dans Jeedom.
> Pour info, si dans un scénario, on veut lancer plusieurs commandes sur différents objets Tuya, il n'y a pas le problème.
> 
> Pour contourner ce problème, il faudrait, dans ce cas, revoir entièrement le développement du plugin.

Bonjour, en ce qui me concerne c est complètement bloquant, je me peux plus utiliser jeedom pour commander 2 appareils en moins de 60 secondes...

**Comment by PhilippeMPerso** [comment]
Bonjour @sabinus52 ,

N'est-il pas possible de stoker dynamiquement le token dans la config du plugin par exemple (je dis ça, mais je connais pas du tout le fonctionnement de Jeedom, c'est juste pour essayer de donner des pistes pour ne pas tout réécrire...)
Comme cela, un scénario qui le récupère le stocke, et tant qu'il est valide, les autres scénarios pourraient utiliser le même? (comme pour le login par exemple)

**Comment by guillaumecardon** [comment]
> Bonjour @sabinus52 ,
> 
> N'est-il pas possible de stoker dynamiquement le token dans la config du plugin par exemple (je dis ça, mais je connais pas du tout le fonctionnement de Jeedom, c'est juste pour essayer de donner des pistes pour ne pas tout réécrire...)
> Comme cela, un scénario qui le récupère le stocke, et tant qu'il est valide, les autres scénarios pourraient utiliser le même? (comme pour le login par exemple)

Je suis en phase avec cette idée.
Comme discuté ici : https://github.com/sabinus52/TuyaCloudApi/issues/4  je pense que si on avait moyen d'extraire (et donc de pouvoir manipuler/stocker) la session (ou même tout l'objet TuyaCloudApi), on pourrait limiter les tentatives d'authentifications et donc ne plus avoir cette erreur.

**Comment by sabinus52** [comment]
> Je suis en phase avec cette idée.
> Comme discuté ici : [sabinus52/TuyaCloudApi#4](https://github.com/sabinus52/TuyaCloudApi/issues/4) je pense que si on avait moyen d'extraire (et donc de pouvoir manipuler/stocker) la session (ou même tout l'objet TuyaCloudApi), on pourrait limiter les tentatives d'authentifications et donc ne plus avoir cette erreur.

Cette est une idée, mais cela implique que le scénario doit être développé en PHP. Ce qui peut rebuter beaucoup d'entre nous.

@dixzerohuit 
> Bonjour, en ce qui me concerne c est complètement bloquant, je me peux plus utiliser jeedom pour commander 2 appareils en moins de 60 secondes...

Chez moi j'arrive à commander 6 appareils dans le même scénario sans problème. Il faudrait surement revoir ton scénario.

**Comment by dixzerohuit** [comment]
Merci mais il m est impossible d utiliser un interrupteur qui éteint une pièce et ses différents équipements et aller dans une autre pièce et allumer avec l'interrupteur en moins de 60 secondes. On ne peut pas faire de scenarios pour toute utilisation...
Pareil pour mes détecteurs d ouverture de porte de placard qui allument la lumière dedans et l'éteignent a la fermeture généralement en moins de 60 secondes

**Comment by guillaumecardon** [comment]
> 
> Cette est une idée, mais cela implique que le scénario doit être développé en PHP. Ce qui peut rebuter beaucoup d'entre nous.
> 

Oui oui bien sûr, c'est pour cela que l'idée que j'ai développé est située sur le git TuyaCloudApi et non sur celui de Jeedom ;)
Je suis d'accord que dans le fond le problème n'est ni lié au plugin, ni à la bilbiothèque utilisée par le plugin, mais bien Tuya :)

**Comment by PhilippeMPerso** [comment]
Disons que la "bonne pratique" veut qu'on utilise un token tant qu'il est valide, pour ne pas se ré-authentifier à chaque requête. Sinon, cela sature le serveur d'authentification pour rien. C'est compréhensible que Tuya ait décidé de mettre cette limitation...
J'imagine que pas mal de gens utilisent ce plugin via des interrupteurs (comme moi), avec donc un scenario par bouton (je ne vois pas comment on peut faire autrement)

**Comment by balabap** [comment]
> Chez moi j'arrive à commander 6 appareils dans le même scénario sans problème. Il faudrait surement revoir ton scénario.

Bonjour,
Peut-on avoir un exemple de tes scénarios, car pour ma part, un scénario avec 4 Interrupteurs de volets smartlife,  seulement 1 s'ouvre ou se ferme. ces actions sont faites dans faites en synchrone.
Merci d'avance

**Comment by PhilippeMPerso** [comment]
Bonsoir,
Dans une instance de scenario, on peut allumer ou éteindre autant de prises/lampes qu'on veut, l'authentification ne se fait qu'une seule fois pour tout le scénario.
Dans le cas des interrupteurs, chaque click sur l'interrupteur lance une instance du scénario...d'où le problème... Pas d'autre choix que de changer de plugin...

**Comment by dixzerohuit** [comment]
![Capture d’écran 2020-12-03 à 18 39 28](https://user-images.githubusercontent.com/75202238/101066772-fcf1be80-3596-11eb-9312-7470dd55ada3.png)
Bonsoir,
Je pense avoir le même problème que @balabap seul le premier élément de mon scenario se lance, le reste tombe en erreur.
On ne doit pas faire les scenarios comme vous... (ou mal les faire ?)
Mais de toutes façons, cela ne résoud pas effectivement les commandes unitaires...

**Comment by sabinus52** [comment]
Dans un scénario, on peut lancer autant de commandes que l'on veut à condition de ne pas les lancer en parallèle.
@dixzerohuit dans ton scénario, je ne vois vraiment pas l'intérêt de lancer les 4 commandes en parallèle sauf pour un besoin spécifique que j'ignore.
Du coup Jeedom exécute autant de thread que de commande et refait une connexion au cloud à chaque thread.

Je vais apporter un correction de fortune pour que les commandes puissent se lancer si une nouvelle connexion se fait mais avec un délai de 60s
La solution est de faire un démon qui conserve la connexion, mais cela implique à revoir complètement le plugin et plusieurs semaines de dev.

**Comment by PhilippeMPerso** [comment]
Bonne nouvelle pour le démon ;) Du coup, ça veut dire que le plugin serait capable de rafraîchir l'état des lampes, si elles ont été modifiées par Alexa ou Google Home par exemple?

**Comment by notesbancales** [comment]
J'ai acheté le plugin pour les sonoffs, j'suis prêt à payer pour avoir un truc qui  marche.
En attendant j'ai fait un compte ifttt par device Smartlife... tant que ça fonctionne... Et ifttt ne voit pas toutes les lampes...
En tout cas merci pour ce plugin  👍

**Comment by PhilippeMPerso** [comment]
J'utilise le plugin Alexa-api en contournement. Il voit toutes mes lampes. Faut juste créer 2 routines par lumières (allume et éteins).
Je pense qu'on serait nombreux à payer pour une mise à jour de ce plugin, car il est très facile à configurer et il n'existe aucune version officielle pour SmartLife sur Jeedom.

**Comment by chemaprados** [comment]
Seulement dans le salon, j'ai 5 groupes de lumières différents, chacun avec un sonoff que j'ai dans smartlife, lié à la compétence Alexa. Quand j'arrive, je dis Alexa, allume une lumière de télévision ou Alexa, j'allume une lumière de canapé, ou Alexa, allume une lumière près de la fenêtre. Il y a beaucoup de combinaisons et je ne vais pas créer de scénario pour chaque combinaison. J'ai ce probleme et c'est que pour allumer 2 sonoff de jeedom je dois attendre 1 minute entre la lumière et la lumière

**Comment by vlar** [comment]
J'ai donc le même soucis mais bien moins souvent depuis le correcif. 

Je ne suis pas sur de comprendre la notion de commandes en parallèle par contre. 
Cela serait dans le cas d'un multi lancement de scénario c'est ça ? 

Mais du coup, plusieurs capteurs de mouvement pour les lumières ne pourront plus fonctionner a moins qu'il y ait 60 secondes d'intervalle entre les différents scénarios ? 

C'est assez horrible de la part de Tuya lol.

**Comment by chemaprados** [comment]
i have solve with wifilight2 plugin.

**Comment by vlar** [comment]
@sabinus52 Je confirme ce que d'autres ont dit. Je serais pour une MAJ payante car en l'état le plugin n'est pas viable du tout pour une gestion de plusieurs lumières.

**Comment by sabinus52** [comment]
@vlar : Dans ton scénario, si tu lances tes commandes en parallèle, Jeedom crée un nouveau thread et du coup refait une nouvelle connexion au Cloud Tuya. A utiliser dans des cas bien particuliers.

Je vais essayer d'apporter une correction, je me lancerai dans le code qu'au mois de janvier et cela peut durer plusieurs semaines.
Je te confirme qu'en aucun cas ce plugin sera payant. Dans ma vie, ce plugin n'est pas ma priorité et je ne peux y consacrer du temps qu'à mes heures perdues.

**Comment by CyrilCharlier** [comment]
@sabinus52 si tu as besoin d'aide, je peux aider mais je ne connais pas la plateforme jeedom , je débute. En revanche je sais coder JS / Php (objet ou procédurale)

**Comment by chemaprados** [comment]
With wifilightv2 plugin works perfect

**Comment by vlar** [comment]
With the wifilightv2 how did you get that Tuya token ? 
You need an Android device for it or do you have any shortcut?

**Comment by chemaprados** [comment]
No! It’s not necesario. You put the Device in ap mode press 2 times reset for 10 seconds. Blink quickly. With a wifi device (iphone, android or laptop) you will be a wifi called ITEAD-xxxxx. Conect to this wifi (password 12345678) and when you will be connect go with browser to url http://10.10.7.1/device and will show id and key for token. It’s very easy. 
device must be with static ip. You could config with your router by MAC address (obtain MAC address by Eweelink app)

**Comment by sabinus52** [comment]
Bonjour,
J'ai apporté une correction pour ne plus avoir cette erreur jusqu'à une nouvelle restriction de Tuya.
Pour le moment cette correction n'est valable que pour la version 4 de Jeedom.
Il reste encore, néanmoins, quelques ajustements mais il n'y a plus cette erreur bloquante.
Merci à Guillaume pour son aide.

**Comment by vlar** [comment]
@sabinus52 Un petit retour n'est pas de trop pour te remercier pour la mise à jour effectuée qui fonctionne très bien.
 Merci.
Je confirme que les erreurs sont à présent marginales voire inexistantes.

**Comment by notesbancales** [comment]
Oui !! Merci beaucoup je viens de faire la maj, jusqu'à présent ça fonctionne !
Super boulot !

**Comment by fitoule** [comment]
@sabinus52  bonjour, le plug a fonctionné une semaine chez moi puis maintenant j'ai cette erreur, pourtant je n'ouvre que 2 Stores.
Je n'ai pas compris les remarques au dessus : ok il ne faut pas lancer en // mais pourquoi dites vous que les actions sont lancées en // dans les screenshot des scenarios ci dessus ? 
Comment faire dans jeedom pour que les 2 actions successives ne soient pas lancées en // ? Faut il mettre un timer d'attente ??
