### ISSUE TITLE
Thermostat BECA BHT-002 / aucun logs

### ISSUE THREAD

**Issue by matthloplop** [sabinus52/jeedom-smartlife#55]
Bonsoir,

Tout d’abords un grand merci pour ton plugin !

J'ai un soucis sur la gestion de mon thermostat Beca BHT-002 avec ton plugin.

Je le manage avec l'application SmartLife.
Le couplage du plugin avec smartlife fonctionne et la découverte me permet de récupérer mon thermostat (de type "climate") avec les commandes associées.
Par contre aucune commande ne fonctionne.
Étrangement, je mets le niveau de logs du plugin en mode debug mais je ne récupère aucun logs.

Aurais tu des orientations à me donner pour troubleshooter?
Merci d'avance

**Comment by matthloplop** [comment]
En complément: j'ai essayé, bien entendu, de désinstaller/réinstaller le plugin et tenté d'activer différents niveau de logs.

**Comment by sabinus52** [comment]
Bonjour,

Pour pouvoir t'aider, j'ai besoin des logs en mode debug

**Comment by matthloplop** [comment]
Bonjour,
Je propose de continuer la discussion sur le forum:
https://community.jeedom.com/t/smartlife-pb-info-thermostat/45390

**Comment by matthloplop** [comment]
J'ai alimenté de logs le thread de la communauté jeedom.
Merci pour ton aide.
