### ISSUE TITLE
Sauvegarde Parent et nom de l'objet impossible

### ISSUE THREAD

**Issue by CyrilCharlier** [sabinus52/jeedom-smartlife#56]
Bonjour,
dès que je change le nom ou le parent de l'objet, le plugin me réinitialise après quelques secondes l'objet à son état "initial".

Est-ce normal ?

merci,

**Comment by sabinus52** [comment]
Merci de poser cette question d'ordre général à Jeedom sur le forum https://community.jeedom.com/.
Rien à voir avec le plugin.

**Comment by CyrilCharlier** [comment]
au moins c'est c'est direct.. circulez y a rien à voir...
