### ISSUE TITLE
Authentification impossible

### ISSUE THREAD

**Issue by sdoub** [sabinus52/jeedom-smartlife#57]
Bonjour,
Je viens d'installer le plugin sur mon jeedom mais impossible de me connecter avec le compte smartlife, pourtant ce même compte est utilisé pour l'association avec mon compte pour amazon/alexa et cela fonctionne très bien. Une idée du pourquoi cela ne fonctionne t il pas avec ce plugin jeedom? 
J'obtiens le message "Get accesstoken failed. Username or password error!"

**Comment by matthloplop** [comment]
Est-ce que l'application SmartLife sur smartphone fonctionne avec ce compte ?

**Comment by sdoub** [comment]
Oui elle fonctionne avec le même compte sur téléphone

**Comment by sabinus52** [comment]
Bonjour,
Pour les demandes d'assistance, il est préférable d'aller sur le forum Jeedom où d'autres personnes on eu un problème similaire et pourront t'aider.
J'ai déjà vu la réponse sur le forum à ce type de problème qui n'est pas lié vraiment  au plugin mais plus à Cloud Tuya. Personnellement je n'ai pas la solution.

Je ferme ce ticket, merci donc d'aller sur https://community.jeedom.com/
