### ISSUE TITLE
Lidl radiateur soufflant céramique WIFI

### ISSUE THREAD

**Issue by Koumal** [sabinus52/jeedom-smartlife#60]
Bonjour,

Je souhaiterais savoir si le radiateur soufflant de LIDL pourrait éventuellement faire parti des équipements compatibles avec le plugin ?

Merci d'avance.

**Comment by sabinus52** [comment]
Bonjour,

Je ne sais pas si ce radiateur est compatible, il faudrait poser la question sur le forum de Jeedom pour savoir si quelqu'un a déjà tester ce même produit.

Pour ma part, je ne conseille pas d'utiliser le objets Tuya sauf pour jouer ou tester. Il y a trop de souci avec ces types d'objets. Rien ne garantit que l'objet fonctionnera correctement avec le plugin.
