### ISSUE TITLE
Smartlife LIDL cloud

### ISSUE THREAD

**Issue by MysterePMS** [sabinus52/jeedom-smartlife#61]
Bonjour,
Je ne sais pas ci c'est du a un beug ou simplement a une non prise en charge.
J'ai acheté un `Radiateur céramique intelligent wifi` chez Lidl, pour le contrôler depuis mon téléphone j'utilise l'application Lidl Home, sur une groupe d'entraide domotique on m'a conseiller votre plugin pour jeedom sachant que le produit utilisé la construction Tuya, cependant dans la connexion quand je mets mon mail et mon mot de pass de l'application Lidl Home, cela n'est pas reconnu.

**Comment by sabinus52** [comment]
Bonjour,

Je ne peux pas aider à ce sujet, merci de poster sur le forum Jeedom où une personne aurai peut être une solution
