### ISSUE TITLE
Pb de générique : liaison équipements. 

### ISSUE THREAD

**Issue by HerveKr** [sabinus52/jeedom-smartlife#63]
Bonjour
Nous sommes nombreux aujourd'hui à commencer à utiliser le plugin Jeemate, lié à l'appli. Jeemate. 
Celui ci remplace tres avantageusement l'appli officielle . 
Neanmoins, pour le moment, on ne peux pas utiliser ton Plugin; Jeemate utilise les "génériques" ... 
Et là le probleme se corse : 
Pour une Prise il faut lier l'état à l'equipement ... Impossible avec ton plugin. 
Et donc pour une prise on a 3 Tuiles ... 
J'espere que tu comprends mon "charabia" .... 

Prévois tu d'implémenter cela bientot ? 

Un grand merci pour ton plugin !

Hervé

**Comment by sabinus52** [comment]
Bonjour,

Les `types génériques` ont été implémentés depuis au bon moment déjà.
Mais comme tu as fait partie des tous premiers à utiliser mon plugin, il se peut que tes objets sont restés sans type générique.
