### ISSUE TITLE
Récupérer la température d'un thermostat wifi connecté à smartlife

### ISSUE THREAD

**Issue by patrickcharron** [sabinus52/jeedom-smartlife#64]
Bonjour,
J'essaie avec aucun résultat de récupérer la température ambiante du thermostat.
J'arrive à fixer la température de déclanchement ainsi que de créer des scénarii mais toujours pas de température.
Il a-t-il une solution à ce problème ou le code n'est pas prévue pour.
Merci de votre retour,
Patrick

**Comment by sabinus52** [comment]
Bonjour,

Les objets de type `climate` posent de problèmes de compatibilité en fonction des fabricants car ils ne ne remontent tout simplement pas l'info. Pour le savoir, il me faudrait les logs en mode DEBUG.
