### ISSUE TITLE
LED Controller WT5 Tuya

### ISSUE THREAD

**Issue by romano3ds** [sabinus52/jeedom-smartlife#65]
Bonjour, j'ai installé sur mon application Tuya un controller LED référencé WT5 (RGB WW CCT).
Il est bien remonté sur le plugin Smartlife mais je n'ai accès qu'à la gestion de la luminosité (on off -> OK, luminosité -> OK).
J'ai en plus la commande de blanc, mais elle ne fait pas réagir le bandeau. Enfin aucune commande liée au changement de couleur, rien n'apparaît.
Est-il possible de les rajouter sois même manuellement ? Si besoin je peux aider pour trouver les commandes.
Merci par avance :)

**Comment by romano3ds** [comment]
Je m'auto réponds... j'ai resynchronisé l'équipement et la commande couleur est arrivée et fonctionnelle. Pour la température de blanc, la commande du plugin va de 0 à 100 mais pour que ça fonctionne, la commande devrait être de 0 à 10000 (0 blanc chaud -> 10000 blanc froid).

**Comment by sabinus52** [comment]
Bonjour,

Pour la température, cela dépend du fabricant. Mes lampes vont de 0 à 100. Pour cela tu peux modifier les valeurs min et max dans la configuration de la commande
