### ISSUE TITLE
Ouverture garage non détecte

### ISSUE THREAD

**Issue by antho8686** [sabinus52/jeedom-smartlife#66]
Bonjour,

mon dispositif ouvrant mon garage n est pas détecté dans le plugin, est il possible de l intégrer svp?

Merci

https://fr.aliexpress.com/item/32997953761.html?spm=a2g0o.productlist.0.0.2fac7afdN3Yejn&algo_pvid=ef8a3a83-6661-4cb7-8109-bdd3642770c5&algo_expid=ef8a3a83-6661-4cb7-8109-bdd3642770c5-0&btsid=2100bdf116173623059571794e3290&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

log:

[2021-04-02 13:25:08][DEBUG] : NEW SESSION : anthoxxxx@xxxx.xx (33) smart_life - 5 s
[2021-04-02 13:25:08][DEBUG] : DISCOVERY : TuyaCloudApi::discoverDevices() -> (return=INCACHE)
[2021-04-02 13:25:08][INFO] :  DISCOVERY : Découverte de 0 devices
[2021-04-02 13:25:08][INFO] :  DISCOVERY : === END =====================================================

**Comment by antho8686** [comment]
de plus, je m apercois que la découverte est à 0, est ce un probleme de parametre ou de compatibilité?

**Comment by sabinus52** [comment]
Bonjour,
il faudrait refaire une découverte car je vois que dans le log, cette découverte vient du cache suite surement après plusieurs clics dans un intervalle très court. 
Si la découverte est toujours 0, c'est que le Cloud Tuya ne retourne pas ton objet et qu'il sera alors incompatible avec mon plugin.
Est il reconnu par Alexa ou Google assistant ?

**Comment by sabinus52** [comment]
Sinon, il faut créer des scènes depuis l'application mobile pour piloter des actions sur l'objet.
