### ISSUE TITLE
Arrosage automatique Rainpoint

### ISSUE THREAD

**Issue by Vax1969** [sabinus52/jeedom-smartlife#67]
Bonjour,

J'ai acheté l'équipement suivant : [https://www.rainpointus.com/products/【ttv103wrftwg004wrf】wifi-smart-water-timer-144](url)
Il est bien gérés via l'appli Smart Life du Smartphone mais via le plugin Objets SmarLife/Tuya les 2 modules ne sont pas vu. Mes autres modules (des lampes) sont bien détectées.
Une chance qu'ils soient intégrés ?

Merci.

**Comment by sabinus52** [comment]
Bonjour,

Il me faudrait les logs de la découverte des objets. Mais il est fort probable que le Cloud Tuya ne retourne pas ce type d'objet et du coup il sera incompatible avec mon plugin.
Merci de suivre ma documentation pour le savoir.

**Comment by Vax1969** [comment]
Je ne trouve rien dans le log (en mode debug).
Par contre l'astuce trouvée, c'est au niveau de l'appli smartphone de créer des scénarios (un pour marche et un pour arrêt).
Les scénarios remontent bien dans votre appli Jeedom et permettent de déclencher des actions via Jeedom.
[SmartLife.zip](https://github.com/sabinus52/jeedom-smartlife/files/6644421/SmartLife.zip)

**Comment by sabinus52** [comment]
Effectivement, l'objet n'est pas retourné par le Cloud Tuya.
Donc, il ne reste plus que la solution en créant des scènes dans l'application comme cela a été fait.
