### ISSUE TITLE
Pompe à chaleur Polytropic

### ISSUE THREAD

**Issue by jronzon** [sabinus52/jeedom-smartlife#69]
Bonjour, 

J'ai acquis une pompe a chaleur pour piscine de la marque polytropic. J'ai rajouté la PAC dans l'application Smart Life en choisissant le module Smart Heat Pump et tout fonctionne correctement dans l'application mobile.
Par contre, l'équipement ne remonte pas dans le plugin jeedom.
En activant le mode debug sur les logs, je ne vois rien du tout a part les autres objets connecté que j'ai.
Est-ce possible de l'ajouter dans la découverte Jeedom ?
Cordialement

**Comment by sabinus52** [comment]
Bonjour,

Malheureusement ce type d’objet n’est pas compatible. Il est possible de le contrôler en utilisant les scènes depuis l’appli mobile. Les scènes devraient remontées dans le plugin Jeedom.
