### ISSUE TITLE
Installation du pluggin

### ISSUE THREAD

**Issue by craftsnake** [sabinus52/jeedom-smartlife#7]
Hello,

J'essaie d'installer le plugin sur mon jeedom, en vain, il me faut une autorisation ?
Ou alors je m'y prends comme un manche xD

Merci

**Comment by sabinus52** [comment]
Bonjour,

Soit tu utilises mon dépôt et tu copie le tout dans le dossier plugins de Jeedom. Ou sinon je peux communiquer un code pour pouvoir l'installer depuis le Market de Jeedom.
Dans ce cas, merci de me laisser un message privé depuis le site https://community.jeedom.com/ (même pseudo)

**Comment by craftsnake** [comment]
Bonjour, Merci pour ta réponse, 
Lorsque j'essaie de l'installer directement dans pluggin, j'ai 3 messages d'erreur : impossible d'envoyer : .gitignore ( x2) et .htaccess.
Le dossier apparaît bien dans le dossier pluggin mais pas dans la gestion dans Jeedom.

Du coup, je vais te faire la demande via un MP depuis Jeedom :)

Merci
