### ISSUE TITLE
Ventilateur de plafond

### ISSUE THREAD

**Issue by jamatba** [sabinus52/jeedom-smartlife#70]
Bonjour,

J'ai acheté un ventilateur de plafond de marque SULION. J'ai ajouté le ventilateur à l'application Smart Life en choisissant le module de ventilateur wifi avec lumière et tout fonctionne bien sur l'application mobile.

Par contre, l'équipement ne remonte pas dans le plugin jeedom.
En activant le mode debug sur les logs, je vois:

[2021-08-03 09:11:16][INFO] :  DISCOVERY : Objet non pris en compte bff7d50d7583f7fe983seg (unknown) : SÛLION CEILING FAN Array (     [online] => 1     [state] => false     [speed_level] => 6     [speed] => 1 )

Est-ce possible de l'ajouter dans la découverte Jeedom ?
Cordialement

**Comment by sabinus52** [comment]
Bonjour,

Malheureusement ce type d’objet n’est pas compatible. Il est possible de le contrôler en utilisant les scènes depuis l’appli mobile. Les scènes devraient remontées dans le plugin Jeedom.

**Comment by jamatba** [comment]
Merci, funciona!
