### ISSUE TITLE
Connexion impossible à Smartlife

### ISSUE THREAD

**Issue by bjerem** [sabinus52/jeedom-smartlife#72]
Bonjour,

J'ai essayé de mettre en place le plugin, malheuresement la connexion reste en impossible.
J'ai également passé la commande curl donné dans vos informations debug. Le message "Get accesstoken failed. Username or password error!" persiste.

La connexion à Smartlife sur mon smartphone est opérationelle. Ayant des caractères speciaux dans mon mot de passe, j'ai remplacé celui-ci afin d'obtenir le mot de passe le plus simple possible mais toujours sans succès alors que la connexion dans l'application reste opérationnel.

Enfin, une autre personne a tester avec son compte smartlife et rencontre le même problème.

Pour information, la version installée est la 2.0.0 du 2021-02-19 23:04:29 avec Jeedom 4.1.25 sur Raspberry pi 3.

Merci de votre assistance.

**Comment by sabinus52** [comment]
Bonjour,

C'est un problème avec le Cloud API qui est très capricieux sur le choix du login et du mot de passe.
Pour ce type de demande, je t'invite à poster sur le forum de Jeedom ou trouver une réponse dessus.

Désolé, mais je ne peux pas faire grand chose de plus.
