### ISSUE TITLE
Erreur MYSQL à la découverte des objets

### ISSUE THREAD

**Issue by MagnumPiece** [sabinus52/jeedom-smartlife#73]
Bonjour,

Quand j'appuie sur le bouton de découverte des objets, j'ai une erreur MySQL que voici :

``` [MySQL] Error code : 42S22 (1054). Unknown column 'sessionCloudTuya' in 'field list' : INSERT INTO `eqLogic` SET `sessionCloudTuya` = :sessionCloudTuya, `device` = :device, `generic_type` = :generic_type, `eqType_name` = :eqType_name, `isEnable` = :isEnable, `timeout` = :timeout, `category` = :category, `comment` = :comment, `tags` = :tags, `eqReal_id` = :eqReal_id, `object_id` = :object_id, `id` = :id, `name` = :name, `logicalId` = :logicalId, `isVisible` = :isVisible, `order` = :order, `configuration` = :configuration, `display` = :display ```

Merci d'avance !

**Comment by sabinus52** [comment]
Bonjour,

Vu l'erreur, c'est un problème avec le core de Jeedom et non avec le plugin.
