### ISSUE TITLE
Commande couleur non dispo

### ISSUE THREAD

**Issue by ThibaultMoka** [sabinus52/jeedom-smartlife#75]
Bonjour,
Merci pour ce plugin qui m'évite d'investir dans dans nouvelles ampoules Zigbee ! 
J'ai un petit soucis pour la selection des couleurs...
La commande n'est pas disponible :
![Capture d’écran 2021-11-23 à 22 48 25](https://user-images.githubusercontent.com/94802340/143134781-778c99a3-fcff-4b03-9244-1431eeb23c06.png)

Pourtant, dans les logs, une info sur la couleur est envoyée :  
 
![Capture d’écran 2021-11-23 à 22 47 25](https://user-images.githubusercontent.com/94802340/143135175-4eeaa125-c447-4416-8398-b343a6874891.png)

J'ai essayé de rajouter la commande manuellement, sans succès....

Une idée de comment faire ? :) 

Merci

**Comment by sabinus52** [comment]
Malheureusement, il n'est plus possible de changer la couleur sur les ampoules.
Je conseille plutôt du Zigbee pour les ampoules ou sinon utiliser le plugin wifilight qui n'utilise pas le Cloud Tuya et permet de changer la couleur. Mais je crois que toutes les ampoules ne sont pas compatibles
