### ISSUE TITLE
Tuya garage 2 voies

### ISSUE THREAD

**Issue by YAYASIMPSON** [sabinus52/jeedom-smartlife#76]
J'ai acquis un tuyau garage 2 voies le problème c'est que lors de la découverte ça marche parfaitement mais il 'e découvre qu'une porte et donc aucun moyen de faire découvrir l'autre y a t'il un moyen qui m'a échappé ? Merci

**Comment by sabinus52** [comment]
Si le Cloud Tuya ne retourne qu'une porte, c'est qu'il ne peut en gérer qu'une seule. 
Donc pas grand chose d'autre à faire : on est trop dépendant de ce Cloud Tuya qui est au final une très mauvaise solution pour faire de la domotique
