### ISSUE TITLE
Contrôle du retro-éclairage des interrupteurs pour volet

### ISSUE THREAD

**Issue by bwibwi13** [sabinus52/jeedom-smartlife#78]
Bonjour,

Tout d'abord, merci beaucoup pour ce plugin qui me permet de gérer mes volets depuis Jeedom.
C'est un élément important de ma domotique donc merci beaucoup :)

Mes interrupteurs pour volets permettent de contrôler le retro-éclairage des boutons (BackLight dans l'app Smart Life).
Est-ce qu'il serait possible d'ajouter cette fonctionnaltié dans le plugin?
(Pour le détails, je voudrais utiliser ce retro-éclairage comme une veilleuse dans la chambre de mes enfants ;)

J'ai quelques notions de programmation.
Je vais essayer de proposer un pull request mais il va falloir que je comprennes le code d'abord. Donc si vous pouviez me guider, ça pourra m'aider.

Merci d'avance pour votre aide.

**Comment by sabinus52** [comment]
Bonjour,

Je suis ravi de savoir que mon plugin te donne satisfaction pour gérer les volets malgré toutes les restrictions qu'apportent la techno Tuya en Wifi.
Pour ma part, j'ai assez vite déchanté sur leurs objets. C'est vrai que ce n'est pas cher, d'ailleurs c'est bien le seul avantage, mais pour le reste ce n'est que des inconvénients (trop de restrictions, techno fermé, peu de comptabilité entre les objets de même types, etc).
Donc je ne suis pas sûr qu'il soit possible de pouvoir éteindre/allumer la veilleuse car je ne connais pas quelle requête qu'il faut faire au Cloud Tuya (aucune info à ce sujet) pour cela.
Donc tu peux essayer d'utiliser mon API (https://github.com/sabinus52/TuyaCloudApi), il y a des exemples (tester avec les fonctions prédéfinies)
Mais bon courage pour trouver sur le web la bonne requête qui permettra de le faire.

**Comment by bwibwi13** [comment]
Bonjour,

Désolé pour le retour tardif. Je manque cruellement de temps ;)

Merci beaucoup pour ta réponse et pour les infos.

Je n'arrive pas à faire tourner l'exemple de TuyaCloudApi par manque d'un répertoire /vendor (qui est effectivement mentionné dans le .gitignore ;)
Je risque de ne pas avoir le niveau pour faire ces recherches donc. Tant pis.

A tout hasard, est-ce que tu penses que la description de l'API Tuya peut aider?
J'ai trouvé ceci: https://developer.tuya.com/en/docs/iot/s?id=K9gf8rs2668v6
Et ça parle bien du backlight en question..

Cordialement
