### ISSUE TITLE
Integration Telerupteur DooWifi

### ISSUE THREAD

**Issue by dbou342** [sabinus52/jeedom-smartlife#79]
Bonjour,
j'ai intégré mon nouveau telerupteur DooWifi dans mon profil SmartLife. (https://doowifi.fr/fr/module-rail-din/208-module-timer-rail-din-DWF-0315TM-3760332970354.html)
Le composant est bien remonté sur le plugin SmartLife de Jeedom, mais il ne me propose pas les informations de consommation. 
En effet, seules les commandes refresh, status, on et off sont présentes.
Avez-vous la possibilité de corriger cela?

Merci d'avance pour votre temps.

**Comment by sabinus52** [comment]
Bonjour,

Comme déjà indiqué plusieurs fois sur le forum Jeedom, il n'est pas malheureusement pas possible de remonter la consommation. Il faut essayer avec le plugin wifilight2 mais sans garanti je crois.
Dans ma documentation, je déconseille d'ailleurs les produits Tuya.
