### ISSUE TITLE
Et les interrupteurs Muraux ?

### ISSUE THREAD

**Issue by HerveKr** [sabinus52/jeedom-smartlife#8]
Hello,
Penses tu intégrer à plus ou moins long terme dans le plugin les interrupteurs muraux ? 
Type (pour l'exemple) :
https://fr.aliexpress.com/item/32993322716.html?spm=a2g0s.12269583.0.0.678d22ffhpfTBX

Merci de ta réponse
Hervé

**Comment by sabinus52** [comment]
Salut,
Je suppose qu'ils fonctionnent comme pour les prises mais sans garanti.
Par contre, comme pour les prises multiples, les interrupteurs multiples sur une même console ne fonctionneront pas. C'est à dire, on pourra allumer ou éteindre l'ensemble mais pas chaque interrupteur individuellement.

**Comment by HerveKr** [comment]
Ok Merci de ta réponse .
Je dois recevoir bientot un interrupteur compatible, j'essaierai,
Te ferai un retour. 
Merci
