### ISSUE TITLE
elesion

### ISSUE THREAD

**Issue by gblanchet03** [sabinus52/jeedom-smartlife#82]
je viens de commander une prise connectée chez Pearl Diffusion. Le logiciel recommandé pour piloter ces objets est elesion
compatible smartlife tuya.
J'ai par ailleurs jeedom installé sur un raspberrypi et j'ai installé votre plugin.
Dans la configuration seules apparaissent les plateformes SmartLife et Tuya.
Serait il possible d'intégrer elesion ?

**Comment by sabinus52** [comment]
Bonjour,

Il n'est pas possible d'intégrer "elesion". Si les objets sont compatibles tuya alors, il faut utiliser l'application mobile "Tuya" ou sinon utiliser un autre plugin.
