### ISSUE TITLE
Connexion avec un climatiseur LG possible ?

### ISSUE THREAD

**Issue by Cartman34** [sabinus52/jeedom-smartlife#83]
Bonjour,

J'ai un climatiseur LG avec télécommande IR. Mon téléphone Xiaomi peut communiquer avec en IR.
Je cherche une solution et apparemment, il existe des appareils Tuya qui peuvent être utilisés avec votre plugin, zigbee et communiquant avec le climatiseur en IR.

Est-ce possible avec votre plugin ? Est-ce intéressant ou existe-t-il une meilleur solution svp ?

**Comment by sabinus52** [comment]
Bonjour,

Mon plugin ne supporte que les objets Wifi que j'ai mentionnés dans la documentation. 
Je ne suis donc pas sûr qu'il existe un objet de ce type qui fonctionnera avec le plugin.
Je vous conseille de poser votre question dans le forum https://community.jeedom.com/ où d'autres personnes ont peut être la solution.

**Comment by Cartman34** [comment]
Juste, j'en ai parlé avec eux et ils me suggèrent des modules IR qui viennent ensuite se connecter en Wifi, j'ai vu que les appareils Tuya étaient moins couteux. Du coup, j'essaye de voir si je peux en acheter et s'il y a des spécificités à connaître.

**Comment by sabinus52** [comment]
Je ne sais pas, mais il a peut de chance que ce type d'objet soit compatible avec mon plugin.
