### ISSUE TITLE
More command on KETLER KE1608W

### ISSUE THREAD

**Issue by Tontongui** [sabinus52/jeedom-smartlife#84]
Hello 

I have plug a KETLER KE1608W on my jeedom by smartlife/tuya pluggin and the integration is ok. So i have only Refresh/Status/On/Off command but this system have also Power/Tension/Current/Consumption data in Tuya apps. Do you think that it's possible to add this command in the pluggin smartlife?

**Comment by sabinus52** [comment]
Bonjour,

Désolé mais je n'apporte plus de nouvelles fonctionnalités sur ce plugin. 
De plus, je ne pense pas que Cloud API de Tuya puisse retourner ses valeurs. Il ne le faisait pas pour les prises connectées avec mesure de consommation quand j'avais testé.
