### ISSUE TITLE
Récupération de la valeur DPS

### ISSUE THREAD

**Issue by fouille** [sabinus52/jeedom-smartlife#86]
Salut ! 

En python on peut faire ce type d'appel : 

```python
        data = smartplug.status()
        print("set_status() result", data)
        # Voltage # DPS (Data Points)
        print("Voltage            :", (data['dps']['20'])/10,"Voltage")
        # Current # DPS (Data Points)
        print("Current            :", (data['dps']['18'])/1000,"Ampere")
        # Power # DPS (Data Points)
        print("Power              :", (data['dps']['19'])/10,"Watt")
        print('')
 ```

Afin d'avoir les données "electriques" des smart plug, en revanche en PHP je suis moins alaise :-) 
Où pourrais-je ajouter l'appel d'information dans les switch (smart plug) pour parsé les valeurs DPS 20, 19 et 18 ? 

Merci par avance, 
Franck

**Comment by sabinus52** [comment]
Bonjour,

Désolé mais je n'apporte plus de nouvelles fonctionnalités sur ce plugin. 
De plus, je ne pense pas que Cloud API de Tuya puisse retourner ses valeurs. Il ne le faisait pas pour les prises connectées avec mesure de consommation quand j'avais testé.
