### ISSUE TITLE
Disjoncteur intelligent WIFI TUYA "Tongou"

### ISSUE THREAD

**Issue by fabdeb2506** [sabinus52/jeedom-smartlife#88]
Bonjour, est il possible de pouvoir intégrer les Disjoncteur intelligent WIFI TUYA , en effet j'ai équipé 5 logements de ce type de disjoncteur pour faire office d'interrupteur pour gérer la mise en chauffe d'eau sanitaire. 
Merci
![Disjoncteur-intelligent-WIFI-TUYA-mesure-de-puissance-1P-63A-DIN-Rail-pour-maison-intelligente-t-l jpg_80x80 jpg_](https://github.com/sabinus52/jeedom-smartlife/assets/154061928/0d408df6-ca81-4ac6-b6c8-5bfcacfdf967)

**Comment by sabinus52** [comment]
Bonjour,

J'ai abandonné le développement de ce plugin car la technologie Tuya est trop fermée. Il m'est aussi impossible de pouvoir tester les différents objets ne les possédant pas moi même.

Désolé
